version: 1.0.{build}

image: Visual Studio 2017

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

before_build:
- cmd: nuget restore

build:
  verbosity: minimal